### ISSUE TITLE
\Consolidation\SiteProcess\ProcessBase::getOutputAsJson doesn't tolerate empty data

### ISSUE THREAD

**Issue by weitzman** [consolidation/site-process#28]
**Describe the bug or behavior**
When this method is faced with `[]` as output, it strips the brackets and then gives an exception for invalid JSON. But I'm pretty sure that `[]` is valid JSON.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.x
| PHP version     | 7.1
| OS?             | Mac

**Comment by greg-1-anderson** [comment]
Yeah, the method is expecting an associative array wrapped in `{ }`. It throws out anything before and after the curley-braces. This is too restrictive.  It should also accept arrays wrapped in `[ ]`, and even simple strings like `'foo`'.

I'll tighten up the junk-removal.
