### ISSUE TITLE
Unable to decode output into JSON when logging to stdout

### ISSUE THREAD

**Issue by kimpepper** [consolidation/site-process#44]
**Describe the bug or behavior**
When a Drupal site is set up to log to stdout using monolog. When running `drush updb`, the output in ProcessBase.php:170 includes log messages as well as the process output as the $output value. This then causes json_decode() to return NULL at line 182 as it is invalid json.

This happens when running drush updb and an update hooks triggers code that logs messages.

**To Reproduce**
Enable monolog module and set to use a stdout handler:
```
  monolog.handler.stdout:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stdout']
```
Set it as the default.
Run drush updb where an update hook triggers a log message (e.g. queue_mail calling module install)

**Expected behavior**
The log messages are filtered.

**Actual behavior**
```
In ProcessBase.php line 184:

  Unable to decode output into JSON.
```
**Workaround**
The workaround was to disable logging to stdout for CLI operations, however, we can no longer get the logs from drush cron.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.1
| Drupal version? | 8.7.3
| PHP version     | 7.3
| OS?             | Linux

**Additional information**

**Comment by jibran** [comment]
Seems related to #33.

**Comment by greg-1-anderson** [comment]
This configuration is not supported. See #33. Remote commands (e.g. via Drush) cannot have arbitrary log information inserted into their stdout stream.

Can you vary your monolog configuration via an environment variable (maybe select a different config file when an environment variable is set)?
